### PR TITLE
Fix regression with empty target attribute (#1444)

### LINKED ISSUE #1444: Regression: links with empty `target` attribute are ignored since 8.0.14
We're using `testcafe` to run end-to-end tests. For reasons beyond our knowledge and control, this adds empty `target` attributes to "some" links.

Now, we use links with `data-turbo-method="DELETE"`, like in the following:

```html
<a href="/logout" data-turbo-method="DELETE">Logout</a>
```

Which gets modified by `testcafe` to

```html
<a href="/logout" data-turbo-method="DELETE" target>Logout</a>
```

I'm not saying this is a good behaviour!

Up until `turbo@8.0.13`, when clicking that link, a `DELETE` request was executed. Starting `turbo@8.0.14`, the link is ignored by turbo.

I tracked this down to the changes in #1429, which test on the presence of `target` attribute, and the exact value of "_self". But in my example, `target` is an empty string. This is a behavioral difference to the original code and I believe should not be the case.

### PR DESCRIPTION
**Pull request by yujiteshima**
<html>
<body>
<h2 data-start="90" data-end="100">Summary</h2>
<p data-start="102" data-end="326">Fixes a regression introduced in <strong data-start="135" data-end="145">8.0.14</strong> where links with empty <code data-start="169" data-end="177">target</code> attributes<br data-start="188" data-end="191">
(<code data-start="192" data-end="200">target</code> or <code data-start="204" data-end="215">target=""</code>) are ignored by Turbo and fall back to regular <strong data-start="263" data-end="270">GET</strong> navigation<br data-start="281" data-end="284">
instead of respecting <code data-start="306" data-end="325">data-turbo-method</code>.</p>
<p data-start="328" data-end="423">This affects tools like <strong data-start="352" data-end="364">TestCafe</strong> that automatically add empty <code data-start="394" data-end="402">target</code> attributes to links.</p>
<hr data-start="425" data-end="428">
<h2 data-start="430" data-end="443">Root Cause</h2>
<p data-start="445" data-end="543">After <a data-start="451" data-end="503" rel="noopener" target="_new" class="decorated-link" href="https://github.com/hotwired/turbo/pull/1429?utm_source=chatgpt.com">#1429<span aria-hidden="true" class="ms-0.5 inline-block align-middle leading-none"><svg width="20" height="20" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg" data-rtl-flip="" class="block h-[0.75em] w-[0.75em] stroke-current stroke-[0.75]"><path d="M14.3349 13.3301V6.60645L5.47065 15.4707C5.21095 15.7304 4.78895 15.7304 4.52925 15.4707C4.26955 15.211 4.26955 14.789 4.52925 14.5293L13.3935 5.66504H6.66011C6.29284 5.66504 5.99507 5.36727 5.99507 5C5.99507 4.63273 6.29284 4.33496 6.66011 4.33496H14.9999L15.1337 4.34863C15.4369 4.41057 15.665 4.67857 15.665 5V13.3301C15.6649 13.6973 15.3672 13.9951 14.9999 13.9951C14.6327 13.9951 14.335 13.6973 14.3349 13.3301Z"></path></svg></span></a>, the link click handler began checking:</p>
<pre class="overflow-visible!" data-start="545" data-end="634"><div class="contain-inline-size rounded-2xl relative bg-token-sidebar-surface-primary"><div class="sticky top-9"><div class="absolute end-0 bottom-0 flex h-9 items-center pe-2"><div class="bg-token-bg-elevated-secondary text-token-text-secondary flex items-center gap-4 rounded-sm px-2 font-sans text-xs"></div></div></div><div class="overflow-y-auto p-4" dir="ltr"><code class="whitespace-pre! language-javascript"><span><span><span class="hljs-keyword">if</span></span><span> (link.</span><span><span class="hljs-title function_">hasAttribute</span></span><span>(</span><span><span class="hljs-string">"target"</span></span><span>) &amp;&amp; link.</span><span><span class="hljs-property">target</span></span><span> !== </span><span><span class="hljs-string">"_self"</span></span><span>) </span><span><span class="hljs-keyword">return</span></span><span> </span><span><span class="hljs-literal">null</span></span><span>
</span></span></code></div></div></pre>
<p data-start="636" data-end="814">The issue is that <code data-start="654" data-end="667">link.target</code> (DOM property) returns <code data-start="691" data-end="695">""</code> for both <code data-start="705" data-end="716">target=""</code> <strong data-start="717" data-end="724">and</strong> bare <code data-start="730" data-end="738">target</code> attributes,<br data-start="750" data-end="753">
so the <code data-start="760" data-end="773">!== "_self"</code> check causes Turbo to skip interception.</p>
<ul data-start="816" data-end="1014">
<li data-start="816" data-end="880">
<p data-start="818" data-end="880"><strong data-start="818" data-end="838">Before (8.0.13):</strong> Empty/bare <code data-start="850" data-end="858">target</code> attributes worked ✅</p>
</li>
<li data-start="881" data-end="944">
<p data-start="883" data-end="944"><strong data-start="883" data-end="902">After (8.0.14):</strong> Empty/bare <code data-start="914" data-end="922">target</code> attributes broken ❌</p>
</li>
<li data-start="945" data-end="1014">
<p data-start="947" data-end="1014"><strong data-start="947" data-end="959">This PR:</strong> Restores 8.0.13 behavior while keeping the #1429 fix ✅</p>
</li>
</ul>
<hr data-start="1016" data-end="1019">
<h2 data-start="1021" data-end="1030">Change</h2>
<p data-start="1032" data-end="1098">Use <code data-start="1036" data-end="1060">getAttribute("target")</code> instead of the <code data-start="1076" data-end="1084">target</code> DOM property:</p>
<pre class="overflow-visible!" data-start="1100" data-end="1218"><div class="contain-inline-size rounded-2xl relative bg-token-sidebar-surface-primary"><div class="sticky top-9"><div class="absolute end-0 bottom-0 flex h-9 items-center pe-2"><div class="bg-token-bg-elevated-secondary text-token-text-secondary flex items-center gap-4 rounded-sm px-2 font-sans text-xs"></div></div></div><div class="overflow-y-auto p-4" dir="ltr"><code class="whitespace-pre! language-javascript"><span><span><span class="hljs-keyword">const</span></span><span> linkTarget = link.</span><span><span class="hljs-title function_">getAttribute</span></span><span>(</span><span><span class="hljs-string">"target"</span></span><span>)
</span><span><span class="hljs-keyword">if</span></span><span> (linkTarget &amp;&amp; linkTarget !== </span><span><span class="hljs-string">"_self"</span></span><span>) </span><span><span class="hljs-keyword">return</span></span><span> </span><span><span class="hljs-literal">null</span></span><span>
</span></span></code></div></div></pre>
<p data-start="1220" data-end="1233"><strong data-start="1220" data-end="1233">Behavior:</strong></p>
<ul data-start="1235" data-end="1407">
<li data-start="1235" data-end="1278">
<p data-start="1237" data-end="1278"><code data-start="1237" data-end="1243">null</code> (no attribute) → Turbo handles ✅</p>
</li>
<li data-start="1279" data-end="1318">
<p data-start="1281" data-end="1318"><code data-start="1281" data-end="1285">""</code> (empty/bare) → Turbo handles ✅</p>
</li>
<li data-start="1319" data-end="1350">
<p data-start="1321" data-end="1350"><code data-start="1321" data-end="1330">"_self"</code> → Turbo handles ✅</p>
</li>
<li data-start="1351" data-end="1407">
<p data-start="1353" data-end="1407"><code data-start="1353" data-end="1363">"_blank"</code>, <code data-start="1365" data-end="1373">"_top"</code>, etc. → <strong data-start="1382" data-end="1393">Ignored</strong> (unchanged) ✅</p>
</li>
</ul>
<hr data-start="1409" data-end="1412">
<h2 data-start="1414" data-end="1422">Tests</h2>
<p data-start="1424" data-end="1554">Added coverage in functional tests (e.g. <code data-start="1465" data-end="1507">src/tests/functional/navigation_tests.js</code>)<br data-start="1508" data-end="1511">
and method-handling paths where applicable.</p>
<h3 data-start="1556" data-end="1576">Navigation Tests</h3>
<div class="_tableContainer_1rjym_1"><div tabindex="-1" class="group _tableWrapper_1rjym_13 flex w-fit flex-col-reverse">
Case | Expected Behavior | Status
-- | -- | --
<a target> (bare) | Turbo advance | ✅
<a target=""> (empty) | Turbo advance | ✅
<a target="_self"> | Turbo advance | ✅
<a target="_blank"> | Browser navigation | ✅

</div></div>
<hr data-start="2267" data-end="2270">
<h2 data-start="2272" data-end="2287">Reproduction</h2>
<p data-start="2289" data-end="2387">Minimal reproduction available:<br data-start="2320" data-end="2323">
🔗 <a data-start="2326" data-end="2387" rel="noopener" target="_new" class="decorated-link" href="https://github.com/yujiteshima/hotwire-turbo-issue-1444-repro">https://github.com/yujiteshima/hotwire-turbo-issue-1444-repro<span aria-hidden="true" class="ms-0.5 inline-block align-middle leading-none"><svg width="20" height="20" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg" data-rtl-flip="" class="block h-[0.75em] w-[0.75em] stroke-current stroke-[0.75]"><path d="M14.3349 13.3301V6.60645L5.47065 15.4707C5.21095 15.7304 4.78895 15.7304 4.52925 15.4707C4.26955 15.211 4.26955 14.789 4.52925 14.5293L13.3935 5.66504H6.66011C6.29284 5.66504 5.99507 5.36727 5.99507 5C5.99507 4.63273 6.29284 4.33496 6.66011 4.33496H14.9999L15.1337 4.34863C15.4369 4.41057 15.665 4.67857 15.665 5V13.3301C15.6649 13.6973 15.3672 13.9951 14.9999 13.9951C14.6327 13.9951 14.335 13.6973 14.3349 13.3301Z"></path></svg></span></a></p>
<hr data-start="2389" data-end="2392">
<h2 data-start="2394" data-end="2403">Closes</h2>
<p data-start="2405" data-end="2421">Closes <strong data-start="2412" data-end="2421">#1444</strong></p>
<hr data-start="2423" data-end="2426">
<h2 data-start="2428" data-end="2436">Notes</h2>
<ul data-start="2438" data-end="2659" data-is-last-node="" data-is-only-node="">
<li data-start="2438" data-end="2503">
<p data-start="2440" data-end="2503">No impact on standard navigation without <code data-start="2481" data-end="2500">data-turbo-method</code>.</p>
</li>
<li data-start="2504" data-end="2589">
<p data-start="2506" data-end="2589">Preserves all existing external/frame-targeted behavior (<code data-start="2563" data-end="2571">_blank</code>, <code data-start="2573" data-end="2579">_top</code>, etc.).</p>
</li>
<li data-start="2590" data-end="2659" data-is-last-node="">
<p data-start="2592" data-end="2659" data-is-last-node="">Backward compatible with 8.0.13 for empty/bare <code data-start="2639" data-end="2647">target</code> attributes.</p></li></ul>
</body>
</html>Summary

Fixes a regression introduced in 8.0.14 where links with empty target attributes
(target or target="") are ignored by Turbo and fall back to regular GET navigation
instead of respecting data-turbo-method.

This affects tools like TestCafe that automatically add empty target attributes to links.

Root Cause

After [#1429](https://github.com/hotwired/turbo/pull/1429?utm_source=chatgpt.com)
, the link click handler began checking:

if (link.hasAttribute("target") && link.target !== "_self") return null

The issue is that link.target (DOM property) returns "" for both target="" and bare target attributes,
so the !== "_self" check causes Turbo to skip interception.

Before (8.0.13): Empty/bare target attributes worked ✅

After (8.0.14): Empty/bare target attributes broken ❌

This PR: Restores 8.0.13 behavior while keeping the #1429 fix ✅

Change

Use getAttribute("target") instead of the target DOM property:

const linkTarget = link.getAttribute("target")
if (linkTarget && linkTarget !== "_self") return null

Behavior:

null (no attribute) → Turbo handles ✅

"" (empty/bare) → Turbo handles ✅

"_self" → Turbo handles ✅

"_blank", "_top", etc. → Ignored (unchanged) ✅

Tests

Added coverage in functional tests (e.g. src/tests/functional/navigation_tests.js)
and method-handling paths where applicable.

Navigation Tests
Case	Expected Behavior	Status
<a target> (bare)	Turbo advance	✅
<a target=""> (empty)	Turbo advance	✅
<a target="_self">	Turbo advance	✅
<a target="_blank">	Browser navigation	✅
Form/Method Tests
Case	Expected Behavior	Status
<a data-turbo-method="post" target>	POST via Turbo	✅
<a data-turbo-method="post" target="">	POST via Turbo	✅
Reproduction

Minimal reproduction available:
🔗 https://github.com/yujiteshima/hotwire-turbo-issue-1444-repro

Closes

Closes #1444

Notes

No impact on standard navigation without data-turbo-method.

Preserves all existing external/frame-targeted behavior (_blank, _top, etc.).

Backward compatible with 8.0.13 for empty/bare target attributes.

### CODE REVIEW

File: src/util.js [hunk 1]
```diff
@@ -251,7 +251,8 @@ export function findLinkFromClickTarget(target) {
 
   if (!link) return null
   if (link.hasAttribute("download")) return null
-  if (link.hasAttribute("target") && link.target !== "_self") return null
+  const linkTarget = link.getAttribute("target")
+  if (linkTarget && linkTarget !== "_self") return null
```
Comment (packagethief) [inline src/util.js]:
```suggestion

  const linkTarget = link.getAttribute("target")
  if (linkTarget && linkTarget !== "_self") return null
```

**Comment by yujiteshima** [comment]
@packagethief 
Good catch! I've made the following changes:

- Updated test names to match project naming convention (removed backticks, adjusted wording)
- Added blank line in util.js before `const linkTarget` for better readability

Thanks for the review!

**Review by packagethief — APPROVED** [review]
