### PR TITLE
Fix temporary elements disappearing on subsequent GET requests that redirect to a page with data-turbo-temporary elements.

### LINKED ISSUE #1301: Temporary elements are removed after subsequent visits of a GET redirect
[This change](https://github.com/hotwired/turbo/commit/db310ef15ed9e4d0d7b7990220a20abe165ea993#diff-49232cc7df722abcf7e1e45ef4e2598d022895ae6647a0d0ccf3db7d9705b20cL421-R421) introduced a regression. If you have a `data-turbo-temporary` element appear on a page after a GET request that redirects to another page (such as a Rails flash message on a redirect), the temporary element will be shown on the first view, then will be hidden on subsequent visits of the same redirected GET request.

This can be demonstrated in [this sample Rails app](https://github.com/mikepayready/investigate_turbo_cache).

I have a fix with a test case incoming, though I don't know if it causes regressions on [this issue](https://github.com/hotwired/turbo/pull/1102) (referenced from the original commit that introduced this regression).

### PR DESCRIPTION
**Pull request by mikepayready**
Fixes #1301

### CODE REVIEW

File: src/core/drive/visit.js [hunk 1]
```diff
@@ -419,7 +419,9 @@ export class Visit {
 
   async render(callback) {
     this.cancelRender()
-    this.frame = await nextRepaint()
+    await new Promise((resolve) => {
+      this.frame = requestAnimationFrame(() => resolve())
```
Comment (brunoprietog) [inline src/core/drive/visit.js:423]:
```suggestion
      if (document.visibilityState === "hidden") {
        this.frame = setTimeout(() => resolve(), 0)
      } else {
        this.frame = requestAnimationFrame(() => resolve())
      }
```

**Review by brunoprietog — CHANGES_REQUESTED** [review]
Good catch. In order not to introduce a regression, we should incorporate the bifurcation here as well.

File: src/core/drive/visit.js (hunk 1 above)
Comment (brunoprietog) [reply src/core/drive/visit.js:423]: Or shorter:

```suggestion
      this.frame =
        document.visibilityState === "hidden" ? setTimeout(() => resolve(), 0) : requestAnimationFrame(() => resolve())
```

**Review by brunoprietog — APPROVED** [review]
Thanks @mikepayready!
